# ここではprofiles.ymlのサンプルファイルとして保存している
# 本来は~/.dbt/profiles.ymlとして配置され、一般的な開発ではユーザーごとに分離される
# DBT_SCHEMA=dev_XXX, # schema: "{{ env_var('dev_XXX', 'dev') }}"
dap_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      dbname: "{{ env_var('ANALYTICS_DB') }}"
      schema: dev
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      dbname: "{{ env_var('ANALYTICS_DB') }}"
      schema: prod
