select
    weather_forecast_id,
    city_id,
    (to_timestamp(dt) at time zone 'Asia/Tokyo') as forecast_at,
    created_at,
    updated_at,
    round((temp - 273.15)::numeric, 2) as temperature_celsius,
    round((feels_like - 273.15)::numeric, 2) as feels_like_temperature_celsius,
    round((temp_min - 273.15)::numeric, 2) as minimum_temperature_celsius,
    round((temp_max - 273.15)::numeric, 2) as maximum_temperature_celsius,
    pressure as atmospheric_pressure,
    sea_level as sea_level_pressure,
    grnd_level as ground_level_pressure,
    humidity as humidity_percentage,
    weather_id,
    main as weather_name,
    description as weather_description,
    icon as weather_icon,
    clouds_all as cloud_coverage_percentage,
    speed as wind_speed,
    deg as wind_direction,
    gust as wind_gust,
    visibility as visibility_distance,
    pop as precipitation_probability,
    pod as part_of_day
from {{source('raw', 'weather_forecasts')}}
