select
    current_weather_id,
    city_id,
    (to_timestamp(dt) at time zone 'Asia/Tokyo') as current_weather_at,
    created_at,
    updated_at,
    weather_id,
    main as weather_name,
    description as weather_description,
    icon as weather_icon,
    round((temp - 273.15)::numeric, 2) as temperature_celsius,
    round((feels_like - 273.15)::numeric, 2) as feels_like_temperature_celsius,
    round((temp_min - 273.15)::numeric, 2) as minimum_temperature_celsius,
    round((temp_max - 273.15)::numeric, 2) as maximum_temperature_celsius,
    pressure as atmospheric_pressure,
    humidity as humidity_percentage,
    sea_level as sea_level_pressure,
    grnd_level as ground_level_pressure,
    visibility as visibility_distance,
    speed as wind_speed,
    deg as wind_direction,
    gust as wind_gust,
    clouds_all as cloud_coverage_percentage,
    (to_timestamp(sunrise) at time zone 'Asia/Tokyo') as sunrise_at,
    (to_timestamp(sunset)  at time zone 'Asia/Tokyo') as sunset_at
from {{source('raw', 'current_weather')}}
