#!/bin/bash

set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE DATABASE ${SOURCE_DB};
CREATE DATABASE ${ANALYTICS_DB};
CREATE DATABASE ${AIRFLOW_DB};

CREATE USER ${SOURCE_DB_USER} WITH PASSWORD '${SOURCE_DB_PASSWORD}';
CREATE USER ${DLT_DB_USER} WITH PASSWORD '${DLT_DB_PASSWORD}';
CREATE USER ${DBT_DB_USER} WITH PASSWORD '${DBT_DB_PASSWORD}';
CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';

REVOKE CONNECT ON DATABASE ${SOURCE_DB} FROM PUBLIC;
REVOKE CONNECT ON DATABASE ${ANALYTICS_DB} FROM PUBLIC;
REVOKE CONNECT ON DATABASE ${AIRFLOW_DB} FROM PUBLIC;

GRANT CONNECT ON DATABASE ${SOURCE_DB} TO ${SOURCE_DB_USER};
GRANT CONNECT ON DATABASE ${SOURCE_DB} TO ${DLT_DB_USER};
GRANT CONNECT ON DATABASE ${ANALYTICS_DB} TO ${DLT_DB_USER};
GRANT CONNECT ON DATABASE ${ANALYTICS_DB} TO ${DBT_DB_USER};
GRANT CONNECT ON DATABASE ${AIRFLOW_DB} TO ${AIRFLOW_DB_USER};

-- [EL]dlt merge は dataset 用に raw の schema 権限が必要
GRANT CREATE ON DATABASE ${ANALYTICS_DB} TO ${DLT_DB_USER};
-- [ T]dbt --target {dev/prod} は {dev/prod}_staging などの schema を新規作成するために必要
GRANT CREATE ON DATABASE ${ANALYTICS_DB} TO ${DBT_DB_USER};
EOSQL
