#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SOURCE_DB" -f /docker-entrypoint-initdb.d/sql/source.sql

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SOURCE_DB" <<EOSQL
GRANT USAGE, CREATE ON SCHEMA public TO ${SOURCE_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA public TO ${SOURCE_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${SOURCE_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${SOURCE_DB_USER};

GRANT USAGE ON SCHEMA public TO ${DLT_DB_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DLT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DLT_DB_USER};

GRANT USAGE, CREATE ON SCHEMA weather TO ${SOURCE_DB_USER};
GRANT USAGE ON SCHEMA weather TO ${DLT_DB_USER};

GRANT ALL ON ALL TABLES IN SCHEMA weather TO ${SOURCE_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA weather TO ${SOURCE_DB_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA weather TO ${DLT_DB_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA weather TO ${DLT_DB_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA weather GRANT ALL ON TABLES TO ${SOURCE_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA weather GRANT ALL ON SEQUENCES TO ${SOURCE_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA weather GRANT SELECT ON TABLES TO ${DLT_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${SOURCE_DB_USER} IN SCHEMA weather GRANT SELECT ON TABLES TO ${DLT_DB_USER};
EOSQL
