#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ANALYTICS_DB" \
    -f /docker-entrypoint-initdb.d/sql/analytics.sql

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ANALYTICS_DB" <<EOSQL
GRANT USAGE, CREATE ON SCHEMA public TO ${DLT_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA public TO ${DLT_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${DLT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DLT_DB_USER};

GRANT USAGE, CREATE ON SCHEMA public TO ${DBT_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA public TO ${DBT_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${DBT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DBT_DB_USER};

GRANT USAGE, CREATE ON SCHEMA raw TO ${DLT_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA raw TO ${DLT_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA raw TO ${DLT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL ON TABLES TO ${DLT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL ON SEQUENCES TO ${DLT_DB_USER};

GRANT USAGE ON SCHEMA raw TO ${DBT_DB_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO ${DBT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO ${DBT_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DLT_DB_USER} IN SCHEMA raw
    GRANT SELECT ON TABLES TO ${DBT_DB_USER};
EOSQL

grant_dbt_write() {
    local schema_name="$1"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ANALYTICS_DB" <<EOSQL
GRANT USAGE, CREATE ON SCHEMA ${schema_name} TO ${DBT_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA ${schema_name} TO ${DBT_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA ${schema_name} TO ${DBT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema_name} GRANT ALL ON TABLES TO ${DBT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema_name} GRANT ALL ON SEQUENCES TO ${DBT_DB_USER};
EOSQL
}

for schema_name in \
    dev_staging dev_intermediate dev_marts dev_seed dev_snapshots \
    prod_staging prod_intermediate prod_marts prod_seed prod_snapshots
do
    grant_dbt_write "$schema_name"
done
