#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AIRFLOW_DB" <<EOSQL
GRANT USAGE, CREATE ON SCHEMA public TO ${AIRFLOW_DB_USER};
GRANT ALL ON ALL TABLES IN SCHEMA public TO ${AIRFLOW_DB_USER};
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${AIRFLOW_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${AIRFLOW_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${AIRFLOW_DB_USER};
EOSQL
